function cycle = psa_cycle_definition(par)
%PSA_CYCLE_DEFINITION Define PSA cycle steps and valve logic.
%   Returns array of step structs with fields:
%   name, duration, bed_high (1 or 2), valves (struct),
%   flow_setpoints (struct).

% Helper to build valve state struct with Cv if provided
valve_state = @(mode, open, Cv) struct('mode',mode,'open',open,'Cv',Cv);

% Purge/product flow controllers setpoints (mol/s)
Fc_purge = par.purge_flow;
Fc_prod = par.product_flow;

% Step 1: Equalisation (top/top and bottom/bottom)
step(1).name = 'equalisation';
step(1).duration = 1.0;
step(1).bed_high = 1; % bed 1 initially high
step(1).valves = struct(...
    'feed', valve_state('control', false, par.valves.V1.Cv), ...
    'product', valve_state('ball', false, par.valves.V4.Cv), ...
    'blowdown', valve_state('ball', false, par.valves.V6.Cv), ...
    'purge', valve_state('flow_controller', false, 0), ...
    'eq_top', valve_state('control', true, par.valves.V10.Cv), ...
    'eq_bottom', valve_state('control', true, par.valves.V12.Cv));
step(1).flow_setpoints = struct('purge', Fc_purge, 'product', Fc_prod);

% Step 2: Pressurisation (feed to low-pressure bed)
step(2).name = 'pressurisation';
step(2).duration = 10.0; % placeholder, adjustable
step(2).bed_high = 1;
step(2).valves = struct(...
    'feed', valve_state('control', true, par.valves.V1.Cv), ...
    'product', valve_state('ball', false, par.valves.V4.Cv), ...
    'blowdown', valve_state('ball', false, par.valves.V6.Cv), ...
    'purge', valve_state('flow_controller', false, 0), ...
    'eq_top', valve_state('control', false, par.valves.V10.Cv), ...
    'eq_bottom', valve_state('control', false, par.valves.V12.Cv));
step(2).flow_setpoints = struct('purge', Fc_purge, 'product', Fc_prod);

% Step 3: Back-flow (assist pressurisation)
step(3).name = 'backflow';
step(3).duration = 5.0; % placeholder
step(3).bed_high = 1;
step(3).valves = struct(...
    'feed', valve_state('control', true, par.valves.V1.Cv), ...
    'product', valve_state('ball', false, par.valves.V4.Cv), ...
    'blowdown', valve_state('ball', false, par.valves.V6.Cv), ...
    'purge', valve_state('flow_controller', false, 0), ...
    'eq_top', valve_state('control', false, par.valves.V10.Cv), ...
    'eq_bottom', valve_state('control', false, par.valves.V12.Cv));
step(3).flow_setpoints = struct('purge', Fc_purge, 'product', Fc_prod);

% Step 4: Production (bed_high produces to receiver)
step(4).name = 'production';
step(4).duration = 59.0;
step(4).bed_high = 1;
step(4).valves = struct(...
    'feed', valve_state('control', true, par.valves.V1.Cv), ...
    'product', valve_state('flow_controller', true, 0), ...
    'blowdown', valve_state('ball', false, par.valves.V6.Cv), ...
    'purge', valve_state('flow_controller', false, 0), ...
    'eq_top', valve_state('control', false, par.valves.V10.Cv), ...
    'eq_bottom', valve_state('control', false, par.valves.V12.Cv));
step(4).flow_setpoints = struct('purge', Fc_purge, 'product', Fc_prod);

% Step 5: Blowdown (regenerating bed to vent)
step(5).name = 'blowdown';
step(5).duration = 59.0;
step(5).bed_high = 1;
step(5).valves = struct(...
    'feed', valve_state('control', false, par.valves.V1.Cv), ...
    'product', valve_state('ball', false, par.valves.V4.Cv), ...
    'blowdown', valve_state('ball', true, par.valves.V6.Cv), ...
    'purge', valve_state('flow_controller', false, 0), ...
    'eq_top', valve_state('control', false, par.valves.V10.Cv), ...
    'eq_bottom', valve_state('control', false, par.valves.V12.Cv));
step(5).flow_setpoints = struct('purge', Fc_purge, 'product', Fc_prod);

% Step 6: Purge (counter-current with product gas)
step(6).name = 'purge';
step(6).duration = 59.0;
step(6).bed_high = 1;
step(6).valves = struct(...
    'feed', valve_state('control', false, par.valves.V1.Cv), ...
    'product', valve_state('ball', false, par.valves.V4.Cv), ...
    'blowdown', valve_state('ball', true, par.valves.V6.Cv), ...
    'purge', valve_state('flow_controller', true, 0), ...
    'eq_top', valve_state('control', false, par.valves.V10.Cv), ...
    'eq_bottom', valve_state('control', false, par.valves.V12.Cv));
step(6).flow_setpoints = struct('purge', Fc_purge, 'product', Fc_prod);

% Step 7: Cutting (optional, disabled)
step(7).name = 'cutting';
step(7).duration = 0.0;
step(7).bed_high = 1;
step(7).valves = struct(...
    'feed', valve_state('control', false, par.valves.V1.Cv), ...
    'product', valve_state('ball', false, par.valves.V4.Cv), ...
    'blowdown', valve_state('ball', false, par.valves.V6.Cv), ...
    'purge', valve_state('flow_controller', false, 0), ...
    'eq_top', valve_state('control', false, par.valves.V10.Cv), ...
    'eq_bottom', valve_state('control', false, par.valves.V12.Cv));
step(7).flow_setpoints = struct('purge', Fc_purge, 'product', Fc_prod);

% Build full cycle definition for twin bed (half-cycle then swap)
cycle.steps = step;
cycle.half_cycle_time = sum([step.duration]);

end
