function schedule = psa_default_schedule(params)
%PSA_DEFAULT_SCHEDULE Construct the baseline PSA step schedule.
%   SCHEDULE = PSA_DEFAULT_SCHEDULE(PARAMS) returns the sequence of steps
%   used by the nitrogen PSA simulation, with durations, pressure targets,
%   and inlet/outlet flow information.
%
%   See also PSA_DEFAULT_PARAMETERS, PSA_SIMULATION.

schedule(1) = struct('name', 'Pressurization', ...
                     'type', 'pressurization', ...
                     'duration', 40, ...
                     'P_target', params.feed_pressure, ...
                     'tau_P', 12, ...
                     'F_in', 0.8, ...
                     'F_out', 0.05, ...
                     'y_in', params.feed_composition, ...
                     'product_stream', false, ...
                     'feed_stream', true, ...
                     'waste_stream', false);

schedule(2) = struct('name', 'Adsorption', ...
                     'type', 'adsorption', ...
                     'duration', 150, ...
                     'P_target', params.feed_pressure, ...
                     'tau_P', 25, ...
                     'F_in', 1.1, ...
                     'F_out', 1.0, ...
                     'y_in', params.feed_composition, ...
                     'product_stream', true, ...
                     'feed_stream', true, ...
                     'waste_stream', false);

schedule(3) = struct('name', 'Counter-current blowdown', ...
                     'type', 'depressurization', ...
                     'duration', 70, ...
                     'P_target', params.low_pressure, ...
                     'tau_P', 18, ...
                     'F_in', 0.0, ...
                     'F_out', 1.2, ...
                     'y_in', [0.0, 0.0], ...
                     'product_stream', false, ...
                     'feed_stream', false, ...
                     'waste_stream', true);

schedule(4) = struct('name', 'Purge', ...
                     'type', 'purge', ...
                     'duration', 110, ...
                     'P_target', params.low_pressure * 1.2, ...
                     'tau_P', 22, ...
                     'F_in', 0.25, ...
                     'F_out', 0.35, ...
                     'y_in', params.product_purge_composition, ...
                     'product_stream', false, ...
                     'feed_stream', false, ...
                     'waste_stream', true);

end
